export interface City { name: string; code: string; slug: string; intro: string; local: string }
export const CITIES: City[] = [
  { name: "Avranches", code: "50300", slug: "avranches", intro: "Interventions rapides à Avranches et son agglomération.", local: "À Avranches, les maisons de ville comme les lotissements récents mêlent installations anciennes et équipements modernes. Anthony PRIME intervient dans tout le bassin avranchinais, de la vieille ville à la zone de la Baie, avec des délais courts pour les urgences (fuite, panne de chaudière, coupure électrique)." },
  { name: "Ducey", code: "50220", slug: "ducey", intro: "Plombier, chauffagiste et électricien à Ducey.", local: "À Ducey et dans les communes voisines de la Sélune, les habitations anciennes nécessitent souvent une remise aux normes progressive. Anthony PRIME connaît bien ce bâti : rénovation de salle de bains, remplacement de chaudière fioul ou passage à la pompe à chaleur, il vous conseille selon votre logement et votre budget." },
  { name: "Pontorson", code: "50170", slug: "pontorson", intro: "Artisan à Pontorson pour tous vos travaux.", local: "Entre le Mont-Saint-Michel et la baie, Pontorson compte de nombreuses maisons de caractère et des gîtes. Anthony PRIME intervient pour les particuliers comme pour les hébergeurs : entretien de chaudière, climatisation réversible pour les chambres d'hôtes, ou remise en conformité électrique avant location." },
  { name: "Fougères", code: "35300", slug: "fougeres", intro: "Interventions rapides à Fougères et son agglomération.", local: "Sur le pays de Fougères, les maisons en pierre et les pavillons des années 70-80 demandent des solutions adaptées à chaque époque de construction. Anthony PRIME y installe chaudières à condensation, pompes à chaleur et climatisations réversibles, avec un accompagnement sur les aides (MaPrimeRénov', CEE)." },
  { name: "Saint-Hilaire-du-Harcouët", code: "50600", slug: "saint-hilaire-du-harcouet", intro: "Plombier, chauffagiste et électricien à Saint-Hilaire-du-Harcouët.", local: "À Saint-Hilaire-du-Harcouët, aux portes de la Normandie et de la Bretagne, Anthony PRIME est un interlocuteur de proximité pour les particuliers et les professionnels. Remplacement de chaudière, création de salle de bains, dépannage électrique : il se déplace rapidement dans toute la zone." },
  { name: "Pontaubault", code: "50220", slug: "pontaubault", intro: "Artisan à Pontaubault pour tous vos travaux.", local: "À Pontaubault, à quelques minutes d'Avranches, les résidences principales comme secondaires font appel à Anthony PRIME pour l'entretien annuel des chaudières, l'installation de pompes à chaleur et la rénovation des salles d'eau. Un artisan de confiance, joignable directement." },
  { name: "Antrain", code: "35560", slug: "antrain", intro: "Interventions à Antrain et ses environs.", local: "À Antrain et dans le Val-Couesnon, les longères et maisons de bourg présentent des installations très variées. Anthony PRIME réalise la mise aux normes des tableaux électriques, le remplacement des chauffe-eau et l'installation de climatisations réversibles, en respectant le caractère des bâtiments." },
  { name: "Granville", code: "50400", slug: "granville", intro: "Plombier, chauffagiste et électricien à Granville.", local: "À Granville, entre la Haute-Ville et les quartiers balnéaires, l'humidité saline impose des matériels et des poses adaptés. Anthony PRIME intervient pour les résidences principales et secondaires : rénovation de salle de bains, entretien de chaudière, climatisation réversible et dépannage toute l'année." },
  { name: "Saint-Georges-de-Reintembault", code: "35420", slug: "saint-georges-de-reintembault", intro: "Plombier, chauffagiste et électricien à Saint-Georges-de-Reintembault.", local: "À Saint-Georges-de-Reintembault, à la frontière de l'Ille-et-Vilaine et de la Manche, Anthony PRIME dessert les exploitations agricoles, les maisons de bourg et les écarts. Géothermie, PAC air/eau, chaudières fioul : il maîtrise toutes les énergies et intervient aussi en urgence." },
  { name: "Saint-James", code: "50240", slug: "saint-james", intro: "Plombier, chauffagiste et électricien à Saint-James, votre artisan de proximité.", local: "Basé à Saint-James, Anthony PRIME est votre artisan de proximité dans le canton et au-delà. De la recherche de fuite au remplacement complet de chaudière, en passant par la création de salle de bains et l'installation de pompes à chaleur, il connaît les habitations du secteur et intervient rapidement." },
]
